config/routes.rb
Rails.application.routes.draw do
  resources :enologists
  resources :magazines
  devise_for :users
  resources :strains
  resources :wines
  root 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enologist.rb
class Enologist < ApplicationRecord
    has_many :enologist_magazines
    has_many :magazines, through: :enologist_magazines, dependent: :destroy
    has_many :wine_enologists
    has_many :wines, through: :wine_enologists, dependent: :destroy
    accepts_nested_attributes_for :enologist_magazines, :magazines, reject_if: :all_blank, allow_destroy: true


    def jobs
        @jobs = Array.new
        self.enologist_magazines.each do |e| 
            @jobs.push("#{e.magazine.name} " + "(#{e.role})") 
        end
        @jobs.sort.join(', ')
    end
end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  before_action :set_enologist, only: %i[ show edit update destroy ]

  # GET /enologists or /enologists.json
  def index
    @enologists = Enologist.all
    @magazines = Magazine.all
  end

  # GET /enologists/1 or /enologists/1.json
  def show
  end

  # GET /enologists/new
  def new
    @enologist = Enologist.new
    @enologist.enologist_magazines.build
    @magazines = Magazine.all
    @Wine_enologist = WineEnologist.all

  end

  # GET /enologists/1/edit
  def edit
  end

  # POST /enologists or /enologists.json
  def create
    @enologist = Enologist.new(enologist_params)
    

    respond_to do |format|
      if @enologist.save
        format.html { redirect_to @enologist, notice: "Enologist was successfully created." }
        format.json { render :show, status: :created, location: @enologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologists/1 or /enologists/1.json
  def update
    respond_to do |format|
      if @enologist.update(enologist_params)
        format.html { redirect_to @enologist, notice: "Enologist was successfully updated." }
        format.json { render :show, status: :ok, location: @enologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologists/1 or /enologists/1.json
  def destroy
    @enologist.destroy
    respond_to do |format|
      format.html { redirect_to enologists_url, notice: "Enologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist
      @enologist = Enologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_params
      params.require(:enologist).permit(:name, :age, :country, enologist_magazines_attributes:[:id, :enologist_id, :magazine_id, :role, :_destroy])
    end
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/views/enologists/_enologist_magazine_fields.html.erb
<div class='nested-fields'>   
    <%= f.select :magazine_id, Magazine.all.map{ |m|[m.name, m.id]} %>
    <div class="form-group">
        <%= f.label :role, 'Rol en Revista' %>
        <%= f.select :role, EnologistMagazine.roles.keys %>
    </div>
</div>

app/views/enologists/_form.html.erb
<%= form_with(model: enologist) do |f| %>
  <% if enologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologist.errors.count, "error") %> prohibited this enologist from being saved:</h2>

      <ul>
        <% enologist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <h3>Revista</h3>
  <div id='magazine'>
    <%= f.fields_for :enologist_magazines do |m| %>
      <%= render 'enologist_magazine_fields', :f => m %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'otra revista', f, :enologist_magazines %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enologists/edit.html.erb
<h1>Editing Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Show', @enologist %> |
<%= link_to 'Back', enologists_path %>

app/views/enologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enólogos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>País</th>
      <th>Revista y Rol(es)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologists.each do |enologist| %>
      <tr>
        <td><%= enologist.name %></td>
        <td><%= enologist.age %></td>
        <td><%= enologist.country %></td>
        <td><%= enologist.jobs %></td>
        <td><%= link_to 'Show', enologist %></td>
        <td><%= link_to 'Edit', edit_enologist_path(enologist) %></td>
        <td><%= link_to 'Destroy', enologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Enólogo', new_enologist_path %>
<%= link_to 'Volver al Listado', root_path %>

app/views/enologists/new.html.erb
<h1>New Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Back', enologists_path %>

app/views/enologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @enologist.age %>
</p>

<p>
  <strong>Country:</strong>
  <%= @enologist.country %>
</p>

<%= link_to 'Edit', edit_enologist_path(@enologist) %> |
<%= link_to 'Back', enologists_path %>