config/routes.rb
Rails.application.routes.draw do
  resources :enologists
  resources :magazines
  devise_for :users
  resources :strains
  resources :wines
  root 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains, dependent: :destroy
    has_many :wine_enologists
    has_many :enologists, through: :wine_enologists, dependent: :destroy
    accepts_nested_attributes_for :strains, :wine_strains, :enologists, :wine_enologists,  reject_if: :all_blank, allow_destroy: true


    def recipe
        @percentages = Array.new
        self.wine_strains.each do |winestrain| 
            @percentages.push("#{winestrain.strain.name} " + "(#{winestrain.percentage}%)") 
        end
        @percentages.sort.join(', ')
    end

    def winescore
        @winescores = Array.new
        self.wine_enologists.each do |w|
            @winescores.push("#{w.enologist.name} " + "=#{w.score} puntos")
        end
        @winescores.sort.join(', ')
    end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :ensure_admin, except: [:index, :show]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
    @wine_enologists = WineEnologist.where(wine_id: :id)

  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @wine.wine_strains.build
    @enologists = Enologist.all.order(:name)
    @wine.wine_enologists.build
    @Wine_enologist = WineEnologist.all

  end

  # GET /wines/1/edit
  def edit
    @enologists = Enologist.all.order(:name) 
    @wine.enologists << @enologists
  end

  # POST /wines or /wines.json
  def create
    if current_user.admin?
      @wine = Wine.new(wine_params)
      @enologists = Enologist.all
      @wine.enologists << @enologists
      respond_to do |format|
        if @wine.save
          format.html { redirect_to @wine, notice: "Wine was successfully created." }
          format.json { render :show, status: :created, location: @wine }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @wine.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: 'Solamente Peter está autorizado'
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    def ensure_admin
      unless current_user.admin?
        redirect_to(root_path, notice: 'Solamente autorizado para Peter')
      end
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, wine_strains_attributes:[:id, :strain_id, :percentage, :_destroy], wine_enologists_attributes: [:id, :wine_id, :enologist_id, :score])
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<h3>Cepas</h3>
  <div id="wine_strains">
    <%= form.fields_for :wine_strains do |ws| %>
      <%= render 'wine_strain_fields', :f => ws %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add cepa', form, :wine_strains %>
    </div>
  </div>

  <h3>Puntaje:</h3>
  <div id='wine_enologists'>
    <%= form.fields_for :wine_enologists do |we| %>
      <%= render 'wine_enologist_fields', :f => we %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Calificar', form, :wine_enologists %>
    </div>
  </div> 

  <div class="actions">
    <%= form.submit 'Guardar Vino' %>
  </div>
<% end %>

app/views/wines/_form2.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<h3>Cepas</h3>
  <div id="wine_strains">
    <%= form.fields_for :wine_strains do |ws| %>
      <%= render 'wine_strain_fields', :f => ws %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add cepa', form, :wine_strains %>
    </div>
  </div>

  <h3>Puntaje:</h3>
  <div id='wine_enologists'>
    <%= form.fields_for :wine_enologists do |we| %>
      <%= render 'wine_enologist_fields', :f => we %>
    <% end %>

    <div class='links'>
      <%= link_to_add_association 'Otra Calificación', form, :wine_enologists %>
    </div>
  </div> 

  <div class="actions">
    <%= form.submit 'Guardar Vino' %>
  </div>
<% end %>

app/views/wines/_wine_enologist_fields.erb
<div class='nested-fields'>   
    <div class="field">
        <%= f.label :name %> 
        <select name="wine[enologist_id]">
            <%= @enologists.each do |e| %>
                <option value="<%= e.id %>">
                <%= e.name %>
                </option> 
            <% end %> 
        </select>
    </div>
    <div class="field">
        <%= f.label :score %> 
        <%= f.number_field :score, step: :any %>
    </div>
</div>

app/views/wines/_wine_strain_fields.erb
  <div class="nested-fields">
    <%= f.select :strain_id, Strain.all.map{ |s|[s.name, s.id]} %>
    <div class="form-group">
        <%= f.label :percentage, 'Porcentaje' %>
        <%= f.text_field :percentage, class: 'form-control' %>
    </div>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form2', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<h1>Vinos de Peter</h1>
<p id="notice" class="alert-primary"><%= notice %></p>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cepas Incluidas</th>
      <th>Calificación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.recipe %></td>
        <td><%= wine.winescore %></td>

        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
<%= link_to 'Agregar Nuevo Vino', new_wine_path %><br>
<%= link_to 'Agregar Nuevas Cepas', new_strain_path %><br>
<%= link_to 'Ver Enólogos', enologists_path %><br>
<%= link_to 'Agregar Nuevo Enólogo', new_enologist_path %><br>
<%end%>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>